#include <variant>
#include <type_traits>

// 型リスト
template<typename... Ts> struct type_list {};

// type_list を variant に変換
template<typename List> struct list_to_variant;

template<typename... Ts>
struct list_to_variant<type_list<Ts...>> {
	using type = std::variant<Ts...>;
};

// variant のネストを平坦化
template<typename T>
struct flatten_variant {
	using type = type_list<T>;
};

template<typename... Ts>
struct flatten_variant<std::variant<Ts...>> {
private:
	// 再帰的に展開した型リストを結合
	template<typename... Us>
	struct concat;

	template<typename... Us1, typename... Us2>
	struct concat<type_list<Us1...>, type_list<Us2...>> {
		using type = type_list<Us1..., Us2...>;
	};

	template<typename Head, typename... Tail>
	struct flatten_all;

	template<typename Head, typename... Tail>
	struct flatten_all<Head, Tail...> {
		using type = typename concat<
			typename flatten_variant<Head>::type,
			typename flatten_all<Tail...>::type
		>::type;
	};

	template<>
	struct flatten_all<> {
		using type = type_list<>;
	};

public:
	using type = typename flatten_all<Ts...>::type;
};

// ヘルパー
template<typename T>
using flatten_variant_t = typename list_to_variant<typename flatten_variant<T>::type>::type;

// Generated by GPT-5
